### ISSUE TITLE
Fix dependency

### ISSUE THREAD

**Issue by Ashlett** [Thermondo/tilex#1]
Dependency `httpoison` is necessary for Slack integration. But the way dependencies are set up currently, it is only installed in test environment as a dependency of `wallaby`. We have a fix ready on branch `fix-dep-httpoison` which adds it explicitly. We should try to get it merged upstream, if not possible then in our fork.

#### TO DO
 * [ ] open an issue in https://github.com/hashrocket/tilex to explain our problem and propose a solution (we have a fix and can make a PR)

**Comment by Ashlett** [comment]
@tilboerner I assign this to you, because you created the branch with the fix

**Comment by Ashlett** [comment]
@tilboerner reminder to open the upstream issue. You said you already started to write it? Otherwise I can also take over and open it, just let me know.

**Comment by tilboerner** [comment]
@Ashlett I opened it as a PR and forgot to link it here: https://github.com/hashrocket/tilex/pull/308
