### ISSUE TITLE
Add title to Twitter share text

### ISSUE THREAD

**Issue by anapaulagomes** [Thermondo/tilex#14]
When we click on Twitter share button, the text is composed only by the post URL. Would be nice to have something like:

> "Find the smallest difference with itertools" by tilboerner
> https://til.thermondo.de/posts/yzrr7eh8ub-find-the-smallest-difference-with-itertools

**Comment by tilboerner** [comment]
@anapaulagomes Which share button do you mean? The `Tweet` one the [post view][] includes the title:

https://github.com/Thermondo/tilex/blob/d7cbe3c8947379c887e6a07f3dcbfb4de6d23606/lib/tilex_web/templates/shared/post.html.eex#L11-L18

It produces this suggested tweet, for example:

> Today I learned: Find the smallest difference with itertools http://til.thermondo.de/posts/yzrr7eh8ub-find-the-smallest-difference-with-itertools #Python

[post view]: https://til.thermondo.de/posts/yzrr7eh8ub-find-the-smallest-difference-with-itertools

**Comment by anapaulagomes** [comment]
The bug only happens if the user has [Privacy Badger](https://www.eff.org/privacybadger) enabled. :) Thanks, Til.

**Comment by tilboerner** [comment]
> The bug only happens if the user has Privacy Badger enabled.

That's a reasonable trade-off, I think. :balance_scale: 

Anyway, thanks for taking the time to suggest improvements!
